### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kilian57** [Braden1996/garrysmod-fastdl-generator#1]
Will you release a new and compiled version?
I don't know how to work with Python and would love it if you could help me!
Thanks
Kilian

**Comment by PassTheMayo** [comment]
figure it out... **XD**

**Comment by Braden1996** [comment]
You can download and install Python from [here](https://www.python.org/). Once installed, download this repository and execute './src/main.py' in Python. I hope it works out. :)
